require("dotenv").config();
module.exports={
 port:Number(process.env.PORT||3000),
 sessionSecret:process.env.SESSION_SECRET||"change-me",
 adminUsername:process.env.ADMIN_USERNAME||"admin",
 adminPassword:process.env.ADMIN_PASSWORD||"change-me",
 maxRecipients:Number(process.env.MAX_RECIPIENTS||25),
 sendDelayMs:Number(process.env.SEND_DELAY_MS||1000),
 smtpDefaults:{host:process.env.SMTP_HOST||"",port:Number(process.env.SMTP_PORT||587),secure:String(process.env.SMTP_SECURE).toLowerCase()==="true",user:process.env.SMTP_USER||"",pass:process.env.SMTP_PASS||"",from:process.env.MAIL_FROM||process.env.SMTP_USER||""}
};
