require("dotenv").config();
const express=require("express"),session=require("express-session"),rateLimit=require("express-rate-limit"),bcrypt=require("bcryptjs"),Database=require("better-sqlite3"),nodemailer=require("nodemailer"),path=require("path"),fs=require("fs");
const config=require("./config"),app=express();
const db=new Database(path.join(__dirname,"..","data.db"));
db.pragma("journal_mode=WAL");
db.exec(`CREATE TABLE IF NOT EXISTS admins(id INTEGER PRIMARY KEY AUTOINCREMENT,username TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL);CREATE TABLE IF NOT EXISTS settings(key TEXT PRIMARY KEY,value TEXT NOT NULL);CREATE TABLE IF NOT EXISTS emails(id INTEGER PRIMARY KEY AUTOINCREMENT,recipients TEXT NOT NULL,subject TEXT NOT NULL,body TEXT NOT NULL,format TEXT NOT NULL,status TEXT NOT NULL,message_id TEXT,error TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);`);
if(!db.prepare("SELECT id FROM admins WHERE username=?").get(config.adminUsername)) db.prepare("INSERT INTO admins(username,password_hash) VALUES(?,?)").run(config.adminUsername,bcrypt.hashSync(config.adminPassword,12));
function getSetting(k,f=""){const r=db.prepare("SELECT value FROM settings WHERE key=?").get(k);return r?r.value:f}
function setSetting(k,v){db.prepare("INSERT INTO settings(key,value) VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value").run(k,String(v??""))}
function smtp(){return{host:getSetting("smtp_host",config.smtpDefaults.host),port:Number(getSetting("smtp_port",config.smtpDefaults.port)),secure:getSetting("smtp_secure",String(config.smtpDefaults.secure))==="true",user:getSetting("smtp_user",config.smtpDefaults.user),pass:getSetting("smtp_pass",config.smtpDefaults.pass),from:getSetting("smtp_from",config.smtpDefaults.from)}}
function transport(){const s=smtp();if(!s.host||!s.user||!s.pass)throw Error("SMTP is not configured.");return nodemailer.createTransport({host:s.host,port:s.port,secure:s.secure,auth:{user:s.user,pass:s.pass}})}
function auth(req,res,next){if(!req.session.user)return res.status(401).json({error:"Unauthorized"});next()}
function sleep(ms){return new Promise(r=>setTimeout(r,ms))}
function esc(v){return String(v??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/\"/g,"&quot;").replace(/'/g,"&#39;")}
function buildMail(s,to,subject,body,format){
  const mail={from:s.from||s.user,to,subject};
  if(format!=="html"){mail.text=body;return mail}
  const logoPath=process.env.MAIL_LOGO_PATH||path.join(__dirname,"..","public","logo.png");
  const logoUrl=process.env.MAIL_LOGO_URL||"";
  const dashboardUrl=process.env.MAIL_DASHBOARD_URL||"";
  const supportUrl=process.env.MAIL_SUPPORT_URL||"";
  const year=new Date().getFullYear();
  let logoHtml="";
  if(logoUrl){logoHtml=`<img src="${esc(logoUrl)}" alt="Anime Cloud Hosting" width="250" style="display:block;width:250px;max-width:80%;height:auto;margin:0 auto;border:0">`}
  else if(fs.existsSync(logoPath)){logoHtml=`<img src="cid:anime-cloud-logo" alt="Anime Cloud Hosting" width="250" style="display:block;width:250px;max-width:80%;height:auto;margin:0 auto;border:0">`;mail.attachments=[{filename:"anime-cloud-logo.png",path:logoPath,cid:"anime-cloud-logo"}]}
  else logoHtml=`<div style="font-size:28px;line-height:32px;font-weight:800;letter-spacing:1px;color:#fff">ANIME <span style="color:#38bdf8">CLOUD</span></div><div style="margin-top:6px;font-size:11px;letter-spacing:5px;color:#dbeafe">— HOSTING —</div>`;
  const safeBody=body;
  const actionButtons=(dashboardUrl||supportUrl)?`<table role="presentation" cellpadding="0" cellspacing="0" border="0" style="margin:26px auto 0"><tr>${dashboardUrl?`<td style="padding:0 5px 8px"><a href="${esc(dashboardUrl)}" style="display:inline-block;background:#1677ff;background:linear-gradient(135deg,#2563eb,#06b6d4);color:#fff;text-decoration:none;font-weight:700;font-size:14px;padding:13px 22px;border-radius:9px">View Dashboard&nbsp; →</a></td>`:""}${supportUrl?`<td style="padding:0 5px 8px"><a href="${esc(supportUrl)}" style="display:inline-block;background:#0b1735;color:#fff;text-decoration:none;font-weight:700;font-size:14px;padding:13px 22px;border-radius:9px;border:1px solid #2b4f91">Contact Support&nbsp; →</a></td>`:""}</tr></table>`:"";
  const html=`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(subject)}</title><style>@media only screen and (max-width:600px){.wrap{width:100%!important}.pad{padding:24px 18px!important}.hero{padding:34px 18px!important}.title{font-size:24px!important}.feature{display:block!important;width:100%!important}.btn{width:100%!important}.hide-mobile{display:none!important}}a{color:#1677ff}body{margin:0;padding:0;background:#eef4ff}</style></head><body style="margin:0;padding:0;background:#eef4ff;font-family:Arial,Helvetica,sans-serif;color:#172554"><table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="background:#eef4ff"><tr><td align="center" style="padding:24px 10px"><table role="presentation" class="wrap" width="680" cellpadding="0" cellspacing="0" border="0" style="width:680px;max-width:680px;background:#fff;border-radius:18px;overflow:hidden;box-shadow:0 12px 45px rgba(15,45,100,.12)">
<tr><td class="hero" align="center" style="padding:34px 24px 38px;background:#061431;background-image:linear-gradient(135deg,#061431 0%,#0b2a69 55%,#075985 100%);border-bottom:4px solid #29a9ff"><div style="font-size:11px;letter-spacing:2px;color:#bfdbfe;margin-bottom:20px">✦ POWERING YOUR DIGITAL WORLD</div>${logoHtml}<div style="margin-top:16px;color:#dbeafe;font-size:12px;letter-spacing:2px">YOUR SERVER. OUR CLOUD. LIMITLESS POSSIBILITIES.</div></td></tr>
<tr><td class="pad" style="padding:38px 44px 10px"><div class="title" style="font-size:28px;line-height:36px;font-weight:800;color:#0f1f45;margin:0 0 10px">Hello there! 👋</div><div style="font-size:15px;line-height:25px;color:#475569">Thank you for choosing <strong style="color:#1677ff">Anime Cloud Hosting</strong>. We are excited to have you with us.</div></td></tr>
<tr><td class="pad" style="padding:18px 44px"><table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="background:linear-gradient(135deg,#eff6ff,#f8fbff);border:1px solid #bfdbfe;border-radius:15px"><tr><td style="padding:24px"><div style="font-size:18px;font-weight:800;color:#1261d8;margin-bottom:8px">Your Service is Ready!</div><div style="font-size:14px;line-height:23px;color:#475569">${safeBody}</div>${actionButtons}</td></tr></table></td></tr>
<tr><td class="pad" style="padding:10px 44px 26px"><table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="border:1px solid #e2e8f0;border-radius:15px"><tr><td class="feature" width="25%" align="center" style="padding:20px 8px;border-right:1px solid #e2e8f0"><div style="font-size:24px">⚡</div><div style="font-size:13px;font-weight:800;margin-top:7px">Ultra Fast</div><div style="font-size:11px;color:#64748b;margin-top:5px">NVMe SSD</div></td><td class="feature" width="25%" align="center" style="padding:20px 8px;border-right:1px solid #e2e8f0"><div style="font-size:24px">🛡️</div><div style="font-size:13px;font-weight:800;margin-top:7px">DDoS Protection</div><div style="font-size:11px;color:#64748b;margin-top:5px">Always On</div></td><td class="feature" width="25%" align="center" style="padding:20px 8px;border-right:1px solid #e2e8f0"><div style="font-size:24px">☁️</div><div style="font-size:13px;font-weight:800;margin-top:7px">99.99% Uptime</div><div style="font-size:11px;color:#64748b;margin-top:5px">Reliable</div></td><td class="feature" width="25%" align="center" style="padding:20px 8px"><div style="font-size:24px">🎧</div><div style="font-size:13px;font-weight:800;margin-top:7px">24/7 Support</div><div style="font-size:11px;color:#64748b;margin-top:5px">Always Here</div></td></tr></table></td></tr>
<tr><td class="pad" style="padding:0 44px 32px"><table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="background:#071735;border-radius:15px"><tr><td style="padding:25px;text-align:center"><div style="font-size:18px;font-weight:800;color:#fff">Need Help or Have Questions?</div><div style="font-size:13px;line-height:21px;color:#cbd5e1;margin-top:7px">Our support team is always ready to assist you.</div>${supportUrl?`<div style="margin-top:16px"><a href="${esc(supportUrl)}" style="display:inline-block;background:#1677ff;color:#fff;text-decoration:none;font-weight:700;font-size:13px;padding:12px 20px;border-radius:8px">Contact Support</a></div>`:""}</td></tr></table></td></tr>
<tr><td style="padding:30px 24px;background:#041126;text-align:center"><div style="font-size:21px;font-weight:800;color:#fff">ANIME <span style="color:#29a9ff">CLOUD</span></div><div style="font-size:10px;letter-spacing:4px;color:#94a3b8;margin-top:6px">— HOSTING —</div><div style="font-size:11px;color:#64748b;margin-top:18px">Your server. Our cloud. Limitless possibilities.</div><div style="height:1px;background:#1e335b;margin:20px auto;max-width:520px"></div><div style="font-size:11px;color:#64748b">© ${year} Anime Cloud Hosting. All rights reserved.</div><div style="font-size:10px;color:#475569;margin-top:7px">This email was sent to ${esc(to)}</div></td></tr>
</table></td></tr></table></body></html>`;
  mail.html=html;return mail;
}
app.use(express.json({limit:"1mb"}));app.use(express.urlencoded({extended:true}));app.use(session({secret:config.sessionSecret,resave:false,saveUninitialized:false,cookie:{httpOnly:true,sameSite:"lax",secure:false,maxAge:28800000}}));app.use(express.static(path.join(__dirname,"..","public")));
app.post("/api/login",rateLimit({windowMs:900000,max:10}),(req,res)=>{const a=db.prepare("SELECT * FROM admins WHERE username=?").get(req.body.username||"");if(!a||!bcrypt.compareSync(req.body.password||"",a.password_hash))return res.status(401).json({error:"Invalid credentials"});req.session.user={id:a.id,username:a.username};res.json({success:true,username:a.username})});
app.post("/api/logout",auth,(req,res)=>req.session.destroy(()=>res.json({success:true})));
app.get("/api/me",(req,res)=>res.json({authenticated:!!req.session.user,user:req.session.user||null}));
app.get("/api/stats",auth,(req,res)=>res.json({total:db.prepare("SELECT COUNT(*) n FROM emails").get().n,sent:db.prepare("SELECT COUNT(*) n FROM emails WHERE status='sent'").get().n,failed:db.prepare("SELECT COUNT(*) n FROM emails WHERE status='failed'").get().n,today:db.prepare("SELECT COUNT(*) n FROM emails WHERE date(created_at)=date('now')").get().n}));
app.get("/api/logs",auth,(req,res)=>{const n=Math.min(Number(req.query.limit||100),200);res.json(db.prepare("SELECT id,recipients,subject,format,status,message_id,error,created_at FROM emails ORDER BY id DESC LIMIT ?").all(n))});
app.get("/api/smtp/settings",auth,(req,res)=>{const s=smtp();res.json({host:s.host,port:s.port,secure:s.secure,user:s.user,from:s.from,configured:!!(s.host&&s.user&&s.pass)})});
app.post("/api/smtp/settings",auth,(req,res)=>{try{const host=String(req.body.host||"").trim(),port=Number(req.body.port||587),user=String(req.body.user||"").trim(),from=String(req.body.from||user).trim(),pass=String(req.body.pass||""),secure=!!req.body.secure;if(!host||!user||!pass)return res.status(400).json({error:"SMTP host, username and password are required."});if(!Number.isInteger(port)||port<1||port>65535)return res.status(400).json({error:"Invalid SMTP port."});setSetting("smtp_host",host);setSetting("smtp_port",port);setSetting("smtp_secure",secure);setSetting("smtp_user",user);setSetting("smtp_from",from||user);setSetting("smtp_pass",pass);res.json({success:true})}catch(e){res.status(500).json({error:e.message})}});
app.get("/api/smtp/status",auth,async(req,res)=>{try{const s=smtp();if(!s.host||!s.user||!s.pass)return res.json({connected:false,configured:false,message:"SMTP is not configured."});await transport().verify();res.json({connected:true,configured:true,host:s.host,port:s.port,secure:s.secure,user:s.user,from:s.from,message:"SMTP connection verified successfully."})}catch(e){const s=smtp();res.json({connected:false,configured:!!(s.host&&s.user&&s.pass),host:s.host,port:s.port,secure:s.secure,user:s.user,from:s.from,message:e.message})}});
app.post("/api/smtp/test",auth,async(req,res)=>{try{await transport().verify();res.json({success:true,message:"SMTP connection verified successfully."})}catch(e){res.status(400).json({success:false,error:e.message})}});
app.post("/api/send",auth,async(req,res)=>{try{let recipients=req.body.recipients;if(typeof recipients==="string")recipients=recipients.split(/[,\n;]/).map(x=>x.trim()).filter(Boolean);if(!Array.isArray(recipients)||!recipients.length)return res.status(400).json({error:"Add at least one recipient."});if(recipients.length>config.maxRecipients)return res.status(400).json({error:`Maximum ${config.maxRecipients} recipients per request.`});const subject=String(req.body.subject||"").trim(),body=String(req.body.body||""),format=req.body.format==="html"?"html":"text";if(!subject||!body)return res.status(400).json({error:"Subject and message are required."});const t=transport(),s=smtp(),results=[];for(const to of recipients){let id;try{id=db.prepare("INSERT INTO emails(recipients,subject,body,format,status) VALUES(?,?,?,?,?)").run(to,subject,body,format,"queued").lastInsertRowid;const info=await t.sendMail(buildMail(s,to,subject,body,format));db.prepare("UPDATE emails SET status='sent',message_id=? WHERE id=?").run(info.messageId,id);results.push({to,status:"sent"})}catch(e){if(id)db.prepare("UPDATE emails SET status='failed',error=? WHERE id=?").run(e.message,id);results.push({to,status:"failed",error:e.message})}if(config.sendDelayMs>0)await sleep(config.sendDelayMs)}res.json({success:true,results})}catch(e){res.status(400).json({error:e.message})}});
app.listen(config.port,()=>console.log(`SMTP Email Dashboard: http://localhost:${config.port}`));
